puts "The students of my cohort at Makers Academy"
puts "_______________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex De Large"
puts "The Alien"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
